export { VesselClient } from "./client.js";
export type { ClientOptions } from "./client.js";
export { VERSION, DEFAULT_BASE_URL } from "./constants.js";
export {
  VesselAPIError,
  VesselAuthError,
  VesselNotFoundError,
  VesselRateLimitError,
  VesselServerError,
  errorFromResponse,
} from "./errors.js";
export { PageIterator } from "./iterator.js";
export type { FetchPage } from "./iterator.js";
export {
  VesselsService,
  PortsService,
  PortEventsService,
  EmissionsService,
  SearchService,
  LocationService,
  NavtexService,
} from "./services.js";

// Re-export all model types
export type {
  GeoJSON,
  PortCountry,
  PortReference,
  VesselReference,
  VesselFormerName,
  BroadcastStation,
  ClassificationPurpose,
  ClassificationCertificate,
  ClassificationCondition,
  ClassificationDimensions,
  ClassificationHull,
  ClassificationIdentification,
  ClassificationInfo,
  ClassificationMachinery,
  ClassificationOwner,
  ClassificationSurvey,
  ClassificationVessel,
  ClassificationYard,
  Vessel,
  VesselResponse,
  VesselPosition,
  VesselPositionResponse,
  VesselPositionsResponse,
  MarineCasualty,
  MarineCasualtiesResponse,
  ClassificationResponse,
  VesselEmission,
  VesselEmissionsResponse,
  VesselETA,
  VesselETAResponse,
  InspectionRecord,
  InspectionDeficiency,
  InspectionDetailRecord,
  InspectionsResponse,
  InspectionDetailResponse,
  VesselOwnership,
  OwnershipResponse,
  Port,
  PortResponse,
  PortEvent,
  PortEventsResponse,
  PortEventResponse,
  FindVesselsResponse,
  FindPortsResponse,
  DGPSStation,
  FindDGPSStationsResponse,
  LightAid,
  FindLightAidsResponse,
  MODU,
  FindMODUsResponse,
  RadioBeacon,
  FindRadioBeaconsResponse,
  VesselsWithinLocationResponse,
  PortsWithinLocationResponse,
  DGPSStationsWithinLocationResponse,
  LightAidsWithinLocationResponse,
  MODUsWithinLocationResponse,
  RadioBeaconsWithinLocationResponse,
  Navtex,
  NavtexMessagesResponse,
} from "./models.js";
